spring.application.name=api-agrovista
api.security.token.secret=${JWT_SECRET:my-secret-key}

#ORACLE
spring.datasource.url=jdbc:oracle:thin:@pradle.fiap.com.br:1521:ORCL
spring.datasource.username=RM558230
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.password=010306

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none